# Form implementation generated from reading ui file 'layout/add_remember.ui'
#
# Created by: PyQt6 UI code generator 6.5.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(175, 144)
        self.verticalLayoutWidget_2 = QtWidgets.QWidget(parent=Dialog)
        self.verticalLayoutWidget_2.setGeometry(QtCore.QRect(10, 10, 161, 131))
        self.verticalLayoutWidget_2.setObjectName("verticalLayoutWidget_2")
        self.main_layout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_2)
        self.main_layout.setContentsMargins(0, 0, 0, 0)
        self.main_layout.setObjectName("main_layout")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.Monday = QtWidgets.QCheckBox(parent=self.verticalLayoutWidget_2)
        self.Monday.setObjectName("Monday")
        self.verticalLayout.addWidget(self.Monday)
        self.Tuesday = QtWidgets.QCheckBox(parent=self.verticalLayoutWidget_2)
        self.Tuesday.setObjectName("Tuesday")
        self.verticalLayout.addWidget(self.Tuesday)
        self.Wednesday = QtWidgets.QCheckBox(parent=self.verticalLayoutWidget_2)
        self.Wednesday.setObjectName("Wednesday")
        self.verticalLayout.addWidget(self.Wednesday)
        self.Thursday = QtWidgets.QCheckBox(parent=self.verticalLayoutWidget_2)
        self.Thursday.setObjectName("Thursday")
        self.verticalLayout.addWidget(self.Thursday)
        self.Friday = QtWidgets.QCheckBox(parent=self.verticalLayoutWidget_2)
        self.Friday.setObjectName("Friday")
        self.verticalLayout.addWidget(self.Friday)
        self.Saturday = QtWidgets.QCheckBox(parent=self.verticalLayoutWidget_2)
        self.Saturday.setObjectName("Saturday")
        self.verticalLayout.addWidget(self.Saturday)
        self.Sunday = QtWidgets.QCheckBox(parent=self.verticalLayoutWidget_2)
        self.Sunday.setObjectName("Sunday")
        self.verticalLayout.addWidget(self.Sunday)
        self.horizontalLayout.addLayout(self.verticalLayout)
        self.timeEdit = QtWidgets.QTimeEdit(parent=self.verticalLayoutWidget_2)
        self.timeEdit.setObjectName("timeEdit")
        self.horizontalLayout.addWidget(self.timeEdit)
        self.main_layout.addLayout(self.horizontalLayout)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.Save = QtWidgets.QPushButton(parent=self.verticalLayoutWidget_2)
        self.Save.setObjectName("Save")
        self.horizontalLayout_2.addWidget(self.Save)
        self.Cancel = QtWidgets.QPushButton(parent=self.verticalLayoutWidget_2)
        self.Cancel.setObjectName("Cancel")
        self.horizontalLayout_2.addWidget(self.Cancel)
        self.main_layout.addLayout(self.horizontalLayout_2)

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.Monday.setText(_translate("Dialog", "Poniedziałek"))
        self.Tuesday.setText(_translate("Dialog", "Wtorek"))
        self.Wednesday.setText(_translate("Dialog", "Środa"))
        self.Thursday.setText(_translate("Dialog", "Czwartek"))
        self.Friday.setText(_translate("Dialog", "Piątek"))
        self.Saturday.setText(_translate("Dialog", "Sobota"))
        self.Sunday.setText(_translate("Dialog", "Niedziela"))
        self.Save.setText(_translate("Dialog", "Zapisz"))
        self.Cancel.setText(_translate("Dialog", "Anuluj"))
