# Form implementation generated from reading ui file 'layout/dodawanie_przegladu.ui'
#
# Created by: PyQt6 UI code generator 6.5.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(458, 159)
        self.verticalLayoutWidget_2 = QtWidgets.QWidget(parent=Dialog)
        self.verticalLayoutWidget_2.setGeometry(QtCore.QRect(10, 10, 402, 134))
        self.verticalLayoutWidget_2.setObjectName("verticalLayoutWidget_2")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_2)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.combo_box_okres = QtWidgets.QComboBox(parent=self.verticalLayoutWidget_2)
        self.combo_box_okres.setObjectName("combo_box_okres")
        self.combo_box_okres.addItem("")
        self.combo_box_okres.addItem("")
        self.combo_box_okres.addItem("")
        self.combo_box_okres.addItem("")
        self.combo_box_okres.addItem("")
        self.gridLayout.addWidget(self.combo_box_okres, 4, 1, 1, 1)
        self.label_samochod = QtWidgets.QLabel(parent=self.verticalLayoutWidget_2)
        self.label_samochod.setObjectName("label_samochod")
        self.gridLayout.addWidget(self.label_samochod, 0, 0, 1, 1)
        self.label_nastepny_przeglad_za = QtWidgets.QLabel(parent=self.verticalLayoutWidget_2)
        self.label_nastepny_przeglad_za.setObjectName("label_nastepny_przeglad_za")
        self.gridLayout.addWidget(self.label_nastepny_przeglad_za, 4, 0, 1, 1)
        self.combo_box_samochod = QtWidgets.QComboBox(parent=self.verticalLayoutWidget_2)
        self.combo_box_samochod.setObjectName("combo_box_samochod")
        self.combo_box_samochod.addItem("")
        self.combo_box_samochod.addItem("")
        self.combo_box_samochod.addItem("")
        self.combo_box_samochod.addItem("")
        self.gridLayout.addWidget(self.combo_box_samochod, 0, 1, 1, 1)
        self.date_edit_data_przegladu = QtWidgets.QDateEdit(parent=self.verticalLayoutWidget_2)
        self.date_edit_data_przegladu.setObjectName("date_edit_data_przegladu")
        self.gridLayout.addWidget(self.date_edit_data_przegladu, 3, 1, 1, 1)
        self.label_data_data_przegladu = QtWidgets.QLabel(parent=self.verticalLayoutWidget_2)
        self.label_data_data_przegladu.setObjectName("label_data_data_przegladu")
        self.gridLayout.addWidget(self.label_data_data_przegladu, 3, 0, 1, 1)
        self.gridLayout.setColumnStretch(0, 1)
        self.verticalLayout.addLayout(self.gridLayout)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.btn_cancel = QtWidgets.QPushButton(parent=self.verticalLayoutWidget_2)
        self.btn_cancel.setObjectName("btn_cancel")
        self.horizontalLayout.addWidget(self.btn_cancel)
        self.btn_submit = QtWidgets.QPushButton(parent=self.verticalLayoutWidget_2)
        self.btn_submit.setObjectName("btn_submit")
        self.horizontalLayout.addWidget(self.btn_submit)
        self.verticalLayout.addLayout(self.horizontalLayout)

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)
        Dialog.setTabOrder(self.combo_box_samochod, self.date_edit_data_przegladu)
        Dialog.setTabOrder(self.date_edit_data_przegladu, self.combo_box_okres)
        Dialog.setTabOrder(self.combo_box_okres, self.btn_cancel)
        Dialog.setTabOrder(self.btn_cancel, self.btn_submit)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dodawanie przeglądu"))
        self.combo_box_okres.setItemText(0, _translate("Dialog", "1 rok"))
        self.combo_box_okres.setItemText(1, _translate("Dialog", "2 lata"))
        self.combo_box_okres.setItemText(2, _translate("Dialog", "3 lata"))
        self.combo_box_okres.setItemText(3, _translate("Dialog", "4 lata"))
        self.combo_box_okres.setItemText(4, _translate("Dialog", "5 lat"))
        self.label_samochod.setText(_translate("Dialog", "Samochód: "))
        self.label_nastepny_przeglad_za.setText(_translate("Dialog", "Następny przegląd za:"))
        self.combo_box_samochod.setItemText(0, _translate("Dialog", "Techtronic"))
        self.combo_box_samochod.setItemText(1, _translate("Dialog", "Moto-Majster"))
        self.combo_box_samochod.setItemText(2, _translate("Dialog", "Techtronic Constractions"))
        self.combo_box_samochod.setItemText(3, _translate("Dialog", "Prywatnie"))
        self.label_data_data_przegladu.setText(_translate("Dialog", "Data przeglądu: "))
        self.btn_cancel.setText(_translate("Dialog", "Anuluj"))
        self.btn_submit.setText(_translate("Dialog", "Dodaj"))
