# Form implementation generated from reading ui file 'ustawienia.ui'
#
# Created by: PyQt6 UI code generator 6.5.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(369, 270)
        self.verticalLayoutWidget = QtWidgets.QWidget(parent=Dialog)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(0, 0, 341, 251))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.ustawienia = QtWidgets.QTabWidget(parent=self.verticalLayoutWidget)
        self.ustawienia.setObjectName("ustawienia")
        self.powiadomienia = QtWidgets.QWidget()
        self.powiadomienia.setEnabled(True)
        self.powiadomienia.setObjectName("powiadomienia")
        self.ustawienia.addTab(self.powiadomienia, "")
        self.itd = QtWidgets.QWidget()
        self.itd.setObjectName("itd")
        self.ustawienia.addTab(self.itd, "")
        self.verticalLayout.addWidget(self.ustawienia)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.pushButton = QtWidgets.QPushButton(parent=self.verticalLayoutWidget)
        self.pushButton.setObjectName("pushButton")
        self.horizontalLayout_2.addWidget(self.pushButton)
        self.verticalLayout.addLayout(self.horizontalLayout_2)

        self.retranslateUi(Dialog)
        self.ustawienia.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.ustawienia.setTabText(self.ustawienia.indexOf(self.powiadomienia), _translate("Dialog", "Powiadomienia"))
        self.ustawienia.setTabText(self.ustawienia.indexOf(self.itd), _translate("Dialog", "ITD"))
        self.pushButton.setText(_translate("Dialog", "PushButton"))
